name: Terraform Cloud Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Write Terraform Cloud Token
      - name: Write Terraform Cloud Token
        run: |
          mkdir -p ~/.terraform.d
          echo '{"credentials":{"app.terraform.io":{"token":"${{ secrets.TFE_TOKEN }}"}}}' > ~/.terraform.d/credentials.tfrc.json

      # Step 3: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 4: Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # Step 5: Terraform Apply (only on main branch)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
